### ISSUE TITLE
source_host is no longer required / needed in logstash 1.2 schema

### ISSUE THREAD

**Issue by rarruda** [logstash/log4j-jsonevent-layout#24]
Shouldnt that field be removed, as it just duplicates data from the field 'host', which gets set by logstash when it runs as an agent ?

**Comment by joekiller** [comment]
Logstash would set host as the logstash agent hostname, unless you are running the logstash agent on the same machine, source_host would be different.  I vote to leave source_host in.  Otherwise perhaps accept pull request #27 so we can append custom data.

**Comment by rarruda** [comment]
I believe that the approach on pullrequest #27 is a valid approach. However one other option could be to set the parameters via log4j itself. Here is a suggestion on how it could be configured:

```
<layout class="net.logstash.log4j.JSONEventLayoutV1">
<param name="UserFields" value="key1:val2[,key2:val2,key3:val3]"/>
<param name="source_host" value="(true|false)"/>
</layout>
```

One issue I have with the current implementation of source_host is that it will create redundant data if you are running the logstash agent locally.

**Comment by lusis** [comment]
@rarruda I'll take a gander. Having this be configurable isn't that painful (though I would default to true since I never find myself running logstash on the same system where I run the code sending it.

Many of the other inputs set a `source_host` iirc and it's how I personally display everything in kibana (by `source_host`)

**Comment by jordansissel** [comment]
In logstash 1.1.x we had a thing "@source_host"

Almost all @-named fields were removed in the schema change in logstash 1.2.0, and this includes removal of @source_host. It was removed because not all input plugins have a concept of "source host". 

Plugins which have an idea of 'source host' simply set the "host" field now. Examples:
- https://github.com/logstash/logstash/blob/master/lib/logstash/inputs/file.rb#L137
- https://github.com/logstash/logstash/blob/master/lib/logstash/inputs/generator.rb#L71
- https://github.com/logstash/logstash/blob/master/lib/logstash/inputs/stdin.rb#L29

Hope this helps!

**Comment by lusis** [comment]
Closing as this is resolved using v0 vs v1
